import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { NavbarDemo } from "@/app/components/Navbar";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en"className="dark">
      <head>
        {/* Add metadata tags if needed */}
      </head>
      <body className={inter.className}>
        <div className="relative w-full flex items-center justify-center "><NavbarDemo /></div>
        
        {children}
      </body>
    </html>
  );
}
